version: '3.9'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5433
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: mb_postgres
    networks:
      - metanet1
    depends_on:
      - mb_postgres
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  mb_postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PORT: 5433
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: metabase
    ports:
      - '5433:5433'
    networks:
      - metanet1
networks:
  metanet1:
    driver: bridge
