steps:
  - name: gradle:6.8-jdk11
    entrypoint: gradle
    args: [ 'bootJar' ]

  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '--build-arg="COMMIT_SHA=${COMMIT_SHA}"', '-t', 'gcr.io/$PROJECT_ID/tilly:$SHORT_SHA', '.' ]

  - name: gcr.io/cloud-builders/gcloud
    args: [ compute, instances, reset, '${_INSTANCE_NAME}', '--zone=${_INSTANCE_ZONE}']

images: [ 'gcr.io/$PROJECT_ID/tilly:$SHORT_SHA' ]

timeout: 3600s
