steps:
  - name: gradle:7.4.2-jdk11
    entrypoint: gradle
    args: [ 'bootJar' ]

  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '--build-arg', 'COMMIT_SHA_ARG=$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/tilly:$SHORT_SHA', '.' ]

  - name: gcr.io/cloud-builders/gcloud
    args: [ compute, instances, update-container, '${_INSTANCE_NAME}', '--container-image=gcr.io/$PROJECT_ID/tilly:$SHORT_SHA', '--zone=${_INSTANCE_ZONE}']

images: [ 'gcr.io/$PROJECT_ID/tilly:$SHORT_SHA' ]

timeout: 3600s
