steps:
  - name: gradle:5.6.2-jdk8
    entrypoint: gradle
    args: ['bootJar']

  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '-t', 'openjdk:11-jre-slim', '--build-arg=JAR_FILE=build/libs/*', '.' ]

images: [ 'gcr.io/tilly-304221/tilly:latest' ]

timeout: 3600s
