steps:
  - name: gradle:5.6.2-jdk8
    entrypoint: gradle
    args: ['bootJar']

  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '-t', 'gcr.io/tilly-304221/tilly:latest', '.' ]

images: [ 'gcr.io/tilly-304221/tilly:latest' ]

timeout: 3600s
