version: '3.8'
services:
  db:
    platform: linux/amd64
    container_name: pg-container
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=tilly
      - POSTGRES_PASSWORD=tilly
      - POSTGRES_DB=tilly
    ports:
      - '5432:5432'
