spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tilly
    driver-class-name: org.postgresql.Driver
    password: tilly
    username: tilly
  cloud:
    gcp:
      vision:
        enabled: false

#telegram:
#  polling-enabled: false
