spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tilly
    driver-class-name: org.postgresql.Driver
    password: tilly
    username: tilly
  cloud:
    gcp:
      vision:
        enabled: false

elasticsearch:
  url: http://localhost

bot:
  id: 1

logs:
  chat:
    id: 1

telegrambots:
  enabled: false
